services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: board-friends
    restart: always
    ports:
      - "5000:5000"
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
